spring:
  application:
    name: connect
  jpa:
    show-sql: true
  output:
    ansi:
      enabled: always                 # ✅ Цветной вывод

logging:
  level:
    root: INFO
    org.springframework: WARN
    org.hibernate: WARN
    com.zaxxer.hikari: WARN

  pattern:
    dateformat: "yyyy-MM-dd HH:mm:ss"  # ✅ Формат даты

app:
  welcome-message: "Welcome to Spring"
  url: ${APP_URL:отсутствует url в переменной окружения!}

rsa:
  private-key: ${RSA_PRIVATE_KEY}
  public-key: ${RSA_PUBLIC_KEY}

yandex:
  storage:
    endpoint: https://storage.yandexcloud.net
    region: ru-central1
    access-key: ${STORAGE_ACCESS_KEY}
    secret-key: ${STORAGE_SECRET_KEY}
    buckets:
      avatars: connect-avatars
      chat-files: connect-chats-files

onesignal:
  base-url: ${ONESIGNAL_BASE_URL}
  app-id: ${ONESIGNAL_APP_ID}
  api-key: ${ONESIGNAL_API_KEY}

server:
  port: 8080
